# Generated by Django 5.1.6 on 2025-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
