# Generated by Django 5.1.6 on 2025-03-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_inventoryitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'permissions': (('manage_inventory', 'Puede administrar el inventario'),)},
        ),
    ]
