# Generated by Django 5.1.6 on 2025-03-01 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0003_alter_inventoryitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='user',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
