# Generated by Django 5.1.6 on 2025-04-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
